# AXIS

* axis=0 for *rows* (top to down)
* axis=1 for *columns* (left to right)

In [1]:
import numpy as np

In [2]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [3]:
arr=np.array(x)

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

* sums all elements down the row

In [5]:
arr.sum(axis=0)

array([12,  8,  9])

* axis=1 sums element in a particular row , all the columns

In [6]:
arr.sum(axis=1)

array([ 6, 15,  8])

* **Transpose** the original matrix

In [7]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

* .flat is used for iterating in items of a matrice

In [8]:
arr.flat

In [9]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


* **.size** gives total element count

In [10]:
arr.size

9

* gives total bytes consumed

In [11]:
arr.nbytes

72

In [12]:
one=np.array([1,3,5,6,34,6])

* argmax gives the index which contains the max value element

In [13]:
one.argmax()

np.int64(4)

In [14]:
one.argmin()

np.int64(0)

* gives indeces for sorting the array

In [15]:
one.argsort()

array([0, 1, 2, 3, 5, 4])

In [16]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [17]:
arr.argmin()

np.int64(8)

In [18]:
arr.argmax()

np.int64(6)

* argmax(axis=0) this gives the max value index in each row

In [19]:
arr.argmax(axis=0)

array([2, 1, 1])

In [20]:
arr.argmax(axis=1)

array([2, 2, 0])

In [21]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

**Matrix Operations**

In [22]:
ar=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [23]:
ar+arr

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [24]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [25]:
arr*ar

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [26]:
arr-ar

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [27]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [28]:
arr.sum()

np.int64(29)

In [29]:
arr.max()

np.int64(7)

In [30]:
arr.min()

np.int64(0)

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

* index of element greater than 5

In [32]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [33]:
np.count_nonzero(arr)

np.int64(8)

In [34]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [35]:
import sys

In [36]:
py_ar=[0,4,55,2]

In [37]:
np_ar=np.array(py_ar)

In [38]:
sys.getsizeof(1)*len(py_ar)

112

In [39]:
np_ar.itemsize * np_ar.size

32

* repeat elements in an array

In [40]:
a=np.array([1,2,3])
r1=np.repeat(a,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]
