### Linspace,Reshape,Arange,Diagonal

In [1]:
import numpy as np

In [2]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [3]:
a[[0,4],[[0,4]]]

array([[ 1, 25]])

* Accessing the diagonal matrix

In [4]:
a[[0,1,2,3,4],[0,1,2,3,4]]

array([ 1,  7, 13, 19, 25])

In [5]:
a.diagonal()

array([ 1,  7, 13, 19, 25])

* Different methods to create the same array using different  methods.

In [6]:
np.linspace(0,1,100).reshape(10,10).round(2)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [7]:
np.arange(0,100).reshape(10,10)/100

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [8]:
a.sum()

np.int64(325)

In [9]:
a.sum(axis=0)

array([55, 60, 65, 70, 75])

In [10]:
sum(a)

array([55, 60, 65, 70, 75])

In [11]:
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

#### Broadcasting :-

In [12]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
a1=a.copy()

In [14]:
a1[1:4,1:4]=0
a1

array([[ 1,  2,  3,  4,  5],
       [ 6,  0,  0,  0, 10],
       [11,  0,  0,  0, 15],
       [16,  0,  0,  0, 20],
       [21, 22, 23, 24, 25]])

In [15]:
a1[0,:]=99
a1

array([[99, 99, 99, 99, 99],
       [ 6,  0,  0,  0, 10],
       [11,  0,  0,  0, 15],
       [16,  0,  0,  0, 20],
       [21, 22, 23, 24, 25]])

* **astype** used for type conversion, from one type to another.

In [16]:
b=a.astype(str)
b

array([['1', '2', '3', '4', '5'],
       ['6', '7', '8', '9', '10'],
       ['11', '12', '13', '14', '15'],
       ['16', '17', '18', '19', '20'],
       ['21', '22', '23', '24', '25']], dtype='<U21')

In [17]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Linear algebra related methods

In [18]:
a.dot(a)

array([[ 215,  230,  245,  260,  275],
       [ 490,  530,  570,  610,  650],
       [ 765,  830,  895,  960, 1025],
       [1040, 1130, 1220, 1310, 1400],
       [1315, 1430, 1545, 1660, 1775]])

* matrix multiplication:-

In [19]:
a@a1

array([[ 313,  209,  214,  219,  369],
       [1078,  814,  824,  834, 1214],
       [1843, 1419, 1434, 1449, 2059],
       [2608, 2024, 2044, 2064, 2904],
       [3373, 2629, 2654, 2679, 3749]])

* another way to create an identity matrix

In [20]:
i= np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

* method to  get the determinant

In [21]:
np.linalg.det(a1)

np.float64(0.0)

In [22]:
c=[[1,2],[3,4]]
c

[[1, 2], [3, 4]]

In [23]:
np.linalg.det(c)

np.float64(-2.0000000000000004)