In [1]:
import numpy as np

In [2]:
arr=np.array([[1,4,5,6,2,3],[2,4,6,8,4,7]])
print(arr)

[[1 4 5 6 2 3]
 [2 4 6 8 4 7]]


* **Shape gives the number of rows , columns**

In [ ]:
arr.shape


(2, 6)

In [4]:
arr.dtype

dtype('int64')

In [ ]:
arr[0,1]
arr[1,2]

4


np.int64(6)

In [8]:
arr[0,1]=99

In [9]:
arr

array([[ 1, 99,  5,  6,  2,  3],
       [ 2,  4,  6,  8,  4,  7]])